#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eclinic")]
public partial class medicineDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public medicineDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["eclinicConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public medicineDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public medicineDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public medicineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public medicineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<MedicineMaster> MedicineMasters
	{
		get
		{
			return this.GetTable<MedicineMaster>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MedicineMaster")]
public partial class MedicineMaster
{
	
	private int _id;
	
	private string _MedicineName;
	
	private System.Nullable<int> _Qty;
	
	private System.Nullable<double> _Price;
	
	private string _Branch;
	
	public MedicineMaster()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="VarChar(MAX)")]
	public string MedicineName
	{
		get
		{
			return this._MedicineName;
		}
		set
		{
			if ((this._MedicineName != value))
			{
				this._MedicineName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
	public System.Nullable<int> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this._Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
	public System.Nullable<double> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this._Price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(50)")]
	public string Branch
	{
		get
		{
			return this._Branch;
		}
		set
		{
			if ((this._Branch != value))
			{
				this._Branch = value;
			}
		}
	}
}
#pragma warning restore 1591
