<?xml version="1.0" encoding="utf-8"?><Database Name="eclinic" Class="medicineDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SOMILLOHANI;Initial Catalog=eclinic;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="eclinicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MedicineMaster" Member="MedicineMasters">
    <Type Name="MedicineMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicineName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>